[package]
name = "proka-fs"
version = "0.1.2"
authors = ["zhangxuan2011 <zx20110412@outlook.com>"]
edition = "2024"
description = "The filesystem of ProkaOS, which is light and simple"
readme = "../README.md"
license = "GPL-3.0"

[dependencies]

[features]
default = []
std = []